// components/ui/icons.tsx
import {
  AlertCircle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  Card,
  FilePlus,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  LogOut,
  Mail,
  Moon,
  MoreVertical,
  Phone,
  Plus,
  Settings,
  Sun,
  Trash,
  Twitter,
  User,
  X,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertCircle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  fileText: FileText,
  filePlus: FilePlus,
  check: Check,
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  phone: Phone,
  mail: Mail,
  logout: LogOut,
  twitter: Twitter,
  image: Image,
  alertCircle: AlertCircle,
};
